#!/bin/bash
hs=("header.h" "conditional.h" "mem.h" "io.h" "linkedlist.h" "pin.h" "concat.h" "library.h")
source_dir="include"
target="pio.h"

# cd into script directory
cd "$(dirname "$0")"

rm -f "$target"

for h in "${hs[@]}"; do
    # copy file and remove empty lines
    grep -v -e '#include\s*\"\w*\.h\"' -v -e '^$' "$source_dir/$h" >> "$target"
done
